name: Format
on: [pull_request]
env:
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
  TERM: xterm-256color
  FORCE_COLOR: true
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install StyLua
        run: |
          curl -LO https://github.com/JohnnyMorganz/StyLua/releases/download/v0.20.0/stylua-linux-x86_64.zip
          unzip -d /usr/local/bin stylua-linux-x86_64.zip
      - name: Run StyLua
        shell: bash
        run: |
          git fetch origin main:main
          git diff --name-only --diff-filter=AM main...HEAD -- \*.lua |
            xargs --no-run-if-empty stylua --check --color always
